### PR TITLE
fix break change for cLaTeXMath library

### PR DESCRIPTION
**Pull request by PikachuHy**
see
https://github.com/NanoMichael/cLaTeXMath/commit/0359f830d381e400d9941436c63c2ecfe8c197a7#commitcomment-50769555
https://github.com/NanoMichael/cLaTeXMath/pull/68
https://github.com/NanoMichael/cLaTeXMath/pull/70

for cmake, i perfer target-based style.
If possible, I can give a PR that rewrites cmake build files with target-based style.
e.g. https://github.com/NanoMichael/cLaTeXMath/commit/0359f830d381e400d9941436c63c2ecfe8c197a7

### CODE REVIEW

**Comment by PikachuHy** [comment]
> 2 workflows awaiting approval

???

**Comment by blackhole89** [comment]
Ah, it said "First-time contributors need a maintainer to approve running workflows. Learn more."

I clicked the approve button; let's see if it goes through. Thanks for making the PR!

**Comment by PikachuHy** [comment]
Is there any problem with this PR?

**Comment by blackhole89** [comment]
No, I just was too busy to merge it yesterday. Merging it now. Thanks!

**Comment by PikachuHy** [comment]
ok. thanks.

**Comment by sp1ritCS** [comment]
> If possible, I can give a PR that rewrites cmake build files with target-based style.
e.g. NanoMichael/cLaTeXMath@0359f83

You can, however you'll have to keep in mind that @blackhole89's IDE (AFAIK [Codeblocks](https://flathub.org/apps/details/org.codeblocks.codeblocks)) uses cmake internally (also one of the reason why the cmake files are so messy in the first place). As long as you don't break the IDE, there should be no problem.

**Comment by PikachuHy** [comment]
Which version of cmake do you use?

**Comment by sp1ritCS** [comment]
me? I don't build notekit with cmake, as meson is (in my experience) superior.

**Comment by PikachuHy** [comment]
The CLion does not support meson.
I am not familiar with meson.

**Comment by PikachuHy** [comment]
@blackhole89 Which version of cmake do you use?

**Pull request merged**
