### PR TITLE
snap package build

### LINKED ISSUE #36: creating snap package
I have started creating a snap package notekit, but came some trouble with the created build file.
The source is [here](https://github.com/noah1510/notekit/tree/snap) and it is able to compile and create the snap seemingly without problems.

To build the snap package install snapcraft with `snap install snapcraft`, change into the cloned repo, run `git checkout snap` and build the snap using the command `snapcraft --debug`.
You can install the created snap using `sudo snap install notekit_*.snap --devmode --dangerous` but there are problems when executing the program.

Simply running simply calling `notekit` in the console gives the following error:
> /snap/notekit/x1/usr/share/notekit/notekit: error while loading shared libraries: libgtkmm-3.0.so.1: cannot open shared object file: No such file or directory

Running the executable directly using `/snap/notekit/x1/usr/share/notekit/notekit` after setting the data manually using ` export XDG_DATA_DIRS=/snap/notekit/current/usr/share:/usr/local/share:/usr/share` gets the program to launch but parts of the ui are missing and I cannot write stuff.

I have the same problem when compiling the source manually, so it might be a problem with the dependencies.
But all version are at least the version required in the readme (except libfontconfig1-dev which is version 2.12.6-0ubuntu2).
I run the local build on my Linux mint 19.3 computer and the snap package is targeted at ubuntu 18.04 (core18).

Any idea on how to get it to work properly?

### PR DESCRIPTION
**Pull request by noah1510**
closes #36

### CODE REVIEW

**Comment by noah1510** [comment]
I looked through all the changes since there are no changes to the source nothing should break.
In addition to that #25 should be resolved by this, since I used the icon proposal as desktop icon.

Installing the snap also adds the desktop configuration, allowing people to start notekit using the menu but the notekit executable has to be in the PATH for it to work since the configuration simply executes `notekit` .

**Comment by blackhole89** [comment]
Thanks! Some points that need addressing before merge - 

* Since my CMakeLists.txt is autogenerated by a CodeLite plugin, the manual changes to it may not be preserved. In particular, this may affect the debug build cmake switch you introduce.
* The zh_CN package description downright makes a false claim (that you can use it for PDF annotation)...
* Is it okay for the "fake Java class name" in the snap to be com.github.notekit when I use test.notekit in Gtk::Application::create? (I honestly have no idea what capacities modern desktop environments use those strings in...)

**Comment by noah1510** [comment]
> Should add cLaTeXMath support to the snap (basically mirror a54a5a4).

I tried but cmake it too old to generate the makefile.

> Is it okay for the "fake Java class name" in the snap to be com.github.notekit when I use test.notekit in Gtk::Application::create? (I honestly have no idea what capacities modern desktop environments use those strings in...)

Should be, xournal++ does the same, I simply copied it, it simply works.
I think it is just a name you need if you want to prevent multiple instances and stuff like that but honestly I really don't know 🤷‍♂️ .

> The zh_CN package description downright makes a false claim (that you can use it for PDF annotation)...

Again I copied it from xournal++ and modified the things I could understand (English and German seems to be correct) but I don't speak any of the other languages so I simply assumed the description is the same just translated.
Should I remove them so that they can be added back in at a later point?

> Since my CMakeLists.txt is autogenerated by a CodeLite plugin, the manual changes to it may not be preserved. In particular, this may affect the debug build cmake switch you introduce.

Me neither but I had to add it to get it the debugger working properly in vs code.

**Comment by blackhole89** [comment]
> I tried but cmake is too old to generate the makefile.

If it's about the `cmake_minimum_required` in its CMakeLists.txt, you can just manually edit that down to a lower version with no ill effects based on my experience.

> zh_CN

I think it's okay to just remove the second sentence (the comma onwards) there; the first half is the same "create annotations by hand" commentary that all the other languages have. I'll come up with some more fitting desc eventually.

For simplicity's sake, I'll probably just merge it into a separate branch and do the adjustments myself in a bit.

**Comment by noah1510** [comment]
> It would however be good if you could just do the changes to make it build with cLaTeXMath, because I'm already within 500MB of my HD's capacity just installing the snap+dependencies for testing and so probably couldn't get the build requirements for snaps installed on top of that (so I'd probably just break the build process by making those changes blindly).

Okay done, I installed the latest cmake version using pip instead of apt, so the latest cmake version will be used to configure the package.
I uploaded a new build based on the current state to the edge channel, it should have latex support but I cannot test it at the moment.

**Pull request closed without merging**
