### PR TITLE
Removed the clatexmath symlink script

### PR DESCRIPTION
**Pull request by sp1ritCS**
See https://github.com/NanoMichael/cLaTeXMath/pull/40

### CODE REVIEW

**Comment by blackhole89** [comment]
What's making the CI fail? I can't actually find the error in the transcript...

**Comment by sp1ritCS** [comment]
> What's making the CI fail? I can't actually find the error in the transcript...

ubuntu-latest is still still 16.04 or 18-04 idk. It still carries gcc 7.5.0 that doesn't support c++17 (meson is also outdated, thats why the ci currently has to download meson via pip). The correct thing would probably to change ubuntu-latest to ubuntu-20.04 in https://github.com/blackhole89/notekit/blob/177bbdd1787ac1a8a5fd3b379d62ba209db49808/.github/workflows/ci.yml#L13
like this: https://github.com/NanoMichael/cLaTeXMath/blob/a5272f33075d2210e9fb7351309cce4257b1c74e/.github/workflows/ci.yml#L13

**Comment by sp1ritCS** [comment]
Im guessing once https://github.com/NanoMichael/cLaTeXMath/pull/48 is merged, it should work with `ubuntu-latest` too. But because of meson, it might still be worth upgrading to ubuntu-2.04

**Comment by sp1ritCS** [comment]
May you trigger a rebuild?

**Comment by sp1ritCS** [comment]
mind re-running the ci and merging now?

**Comment by blackhole89** [comment]
Just reran it, still seems to have failed.

**Comment by sp1ritCS** [comment]
guessing i have to merge the changes into this branch first

**Comment by sp1ritCS** [comment]
closing due to #87

**Pull request closed without merging**
