### PR TITLE
meson symlink to clatexmath

### PR DESCRIPTION
**Pull request by sp1ritCS**
Note: this works, but I really don't like it

### CODE REVIEW

**Comment by LyesSaadi** [comment]
Yeah... This is a really ugly solution...

**Comment by blackhole89** [comment]
I'm not sure I have a better one... really, if cLaTeXMath is going to be a shared library, it should include its own logic for locating the data files that it needs (so LaTeX::init without a parameter proactively finds them in /usr/share/clatexmath:/usr/local/share/clatexmath:... or whatever else is appropriate for the host system, rather than just looking at res/ relative to the current working directory).

What was the rationale for making it a separate package and dynamically linking against it, rather than following the approach I took in the cmake build scripts and linking it in statically, to begin with?

**Comment by sp1ritCS** [comment]
> What was the rationale for making it a separate package and dynamically linking against it, rather than following the approach I took in the cmake build scripts and linking it in statically, to begin with?

- They're two seperate projects, we should not have to compile cLaTeXMath if notekit gets updated (in a clean build environment like OBS or COPR).
 - We should not have to run a shell script that modifies cmake buildfiles in order to get clatexmath working
- Getting the flatpak package to work with clatexmath w. cmake and static linking would be a pain (it already was with island build rpm, because multiple %cmake macros conflict with eachother)

**Comment by sp1ritCS** [comment]
Letting cLaTeXMath gather the correct location of the res/ folder internally is probably the best option, but if @NanoMichael doen't want to do this, a better workaround than #66 might be to have another var in `config.h` (idk, maybe `CLATEXMATH_RES_PATH`). That Meson configures to `get_option('prefix')get_option('datadir')/clatexmath` and cmake to `/usr/share/notekit/data/latex`.

**Pull request merged**
