### PR TITLE
GSV Markdown improvements

### LINKED ISSUE #72: Multiline LaTeX
I'm unsure if I just don't know how (as it appears as https://github.com/blackhole89/notekit/blob/af313fbd3710ce6e2f0f51e770099b91de3d8ad7/sourceview/markdown.lang#L192 matches $$\n\LaTeX\n$$) or if this is a limitation with gtksourceview (no multiline regex)

It is very hard to know what you want to edit, if you have a huge LaTeX Table (See #47 ) in one line.

### PR DESCRIPTION
**Pull request by sp1ritCS**
- Multiline LaTeX (closes #72 ) 
- Escaped `\$` now only render as `$` 
- Removed four space/double tab codeblocks ( #32 )

Also added a check for NK_DEVEL env var. If set it'll use the value as notekit root

### CODE REVIEW

**Comment by blackhole89** [comment]
Thanks, I'll go check it now! Did the problems about single-$ spans getting centered and rendered in displaystyle get resolved for you?

**Comment by sp1ritCS** [comment]
Yeah, the only issues I had were that Gsv considers EOF the same as any <end> match.

**Comment by blackhole89** [comment]
I actually experienced a lot of issues testing it; the one in the PR didn't highlight several files in my own tree of notes correctly (even though I've only ever used single-line LaTeX in them), and after my fix, trying to actually use it constantly resulted in something blocking the new-character event and Gsv worker threads going into busy loops.

I'm rolling it back for now until I can figure out a more resilient way to implement this. (In the worst case, we might have to resort to just having the syntax highlighter tell us where the $s and $$s are, and running a separate processing step after the highlighting engine to match them up and render their contents.)

**Comment by blackhole89** [comment]
I just committed a battery of fixes to proximity widget handling, which hopefully should get rid of most cases of stray [X] boxes being displayed. Verdict is still out on whether I need to add a manual filter to remove 0xFFFCs that somehow made it past the logic on load/save. It might be worth trying to see if the multiline approach (with the spec of commit d961dadbad75301f5879a3bbdf2b514ba5ce55d4) fails more gracefully now.

**Pull request merged**
