### PR TITLE
Ci using github actions

### PR DESCRIPTION
**Pull request by noah1510**
This pull request contains two actions:
* latest-release.yml compiles every commit on master and if successful, compresses all files in the current folder and uploads them to the latest tag as a release on github.
* ci.yml compiles every commit to all branches except master (even checks pull request to master) but does not upload any release. 

If either of them fails it will upload the current folder as build artifact to make troubleshooting easier.

### CODE REVIEW

**Comment by blackhole89** [comment]
Thanks for this! Unfortunately, I can't seem to be able to get it to actually generate downloadable builds even after giving `latest-release.yml` a distinct `name:` (which was apparently necessary to make Github register it as an action) - it claims to be "passing", but says that "No artifacts were generated." (Maybe you can see [the run log page](https://github.com/blackhole89/notekit/actions/runs/108783375) as well.)

**Comment by noah1510** [comment]
It creates the build as a release, the artifacts are only generated in case some step failed

**Comment by noah1510** [comment]
If you want to always create the artifact change to `if: failure()` to `if: always()` causing the step to always run.

**Comment by noah1510** [comment]
> Unrelatedly, is there a particular reason to use ninja rather than straight GNU make ?)

Ninja is faster and works better with different operating systems

**Pull request merged**
