### PR TITLE
Fix macos build

### PR DESCRIPTION
**Pull request by PikachuHy**
see https://github.com/blackhole89/notekit/issues/120

### CODE REVIEW

**Comment by sp1ritCS** [comment]
Thanks, we were stuck on this one and didn't know how to fix it. Also see #116

**Comment by sp1ritCS** [comment]
In ragrds to the failing mingw build, for some reason [mirrorbrain](https://github.com/openSUSE/mirrorbrain) picks a mirror that doesn't provide repos in the home: namespace. Maybe it's tagged incorrectly, I'll ask the oS heros later.

**Comment by PikachuHy** [comment]
maybe we can add a guard 😭
like this

```cpp
#if defined(__linux__) || defined(_WIN32)
// do nothing
#else
#include <clocale>
#endif

```

**Comment by sp1ritCS** [comment]
no, why would we? it seems to work on linux at least. The buils failures aren't due to your commit. (or doesn't it work on windows?)

**Comment by PikachuHy** [comment]
> In ragrds to the failing mingw build

sorry, I misunderstood what you said.

**Comment by PikachuHy** [comment]
can this PR be merged?

**Comment by sp1ritCS** [comment]
I've asked about it, since I want this merged too. Development is quite slow, unless something affects @blackhole89 himself :)

Screenshot from 2022-04-02 18-51-25

**Comment by blackhole89** [comment]
Argh, sorry! I'm merging it for now, but both the MinGW and the Darwin CI build seem to fail with something pertaining to clatexmath.

**Comment by PikachuHy** [comment]
> both the MinGW and the Darwin CI build seem to fail with something pertaining to clatexmath.

use openmath branch

**Comment by sp1ritCS** [comment]
@PikachuHy 
> use openmath branch

no, that wasn't the issue. Darwin CI was failing with linuxbrew and incorrect libstdc++, #124 fixes that.

newer OS X versions seem to fail with cLaTeXMath however (according to one iMac NoteKit user in the chatroom), so I have set up [sp1ritCS/tap/notekit-sp1rit](https://github.com/sp1ritCS/homebrew-tap/blob/master/Formula/notekit-sp1rit.rb) and [sp1ritCS/tap/microtex](https://github.com/sp1ritCS/homebrew-tap/blob/master/Formula/microtex.rb) that use MicroTeX/openmath. However (likely due to homebrew wierdness) notekit-sp1rit seems to fail to install the datadir and charter fonts property (maybe only when installing the bottle), but I haven't looked further into that.

**Pull request merged**
