### PR TITLE
Improved CI

### PR DESCRIPTION
**Pull request by sp1ritCS**

### CODE REVIEW

**Comment by blackhole89** [comment]
Wait, so what is this supposed to do with cLaTeXMath? I don't see the script that patches it to link statically being invoked here, but a dynamically linked version would have to somehow actually be installed in a place where ld.so can find it (which might not be straightforward in a flat "artifacts" file, unless it is built in a way that you are supposed to extract it to /). In fact, as far as I can tell, the build artifacts file this generates doesn't even seem to contain the data/resource folders...?

**Comment by sp1ritCS** [comment]
It's CI, not the nightly built. This just to see if a pull compiles (and maybe later, test it)

I think we should also improve the nightly build with AppImage, as it doesn't work with most distros (its linked to libjsoncpp.so.1 that is not availible on most distros (usualy libjsoncpp.so.24))

**Comment by blackhole89** [comment]
> It's CI, not the nightly built. This just to see if a pull compiles (and maybe later, test it)

Well, but doesn't the existing automated build already take care of that? It also runs after every commit, rather than being a "nightly".

> I think we should also improve the nightly build with AppImage, as it doesn't work with most distros (its linked to libjsoncpp.so.1 that is not availible on most distros (usualy libjsoncpp.so.24))

It's libjsoncpp.so.1 in Debian derivatives, which still seem to form the (relative) majority of distributions. I'd be happy to set up separate nightly builds for some other families (is the name of libjsoncpp.so the only relevant difference, or are there others?).

Regarding AppImage, I'm still reluctant to make any container-based format *the* default way Notekit is distributed. They all strike me as very inconvenient because of how much space and RAM they use, and I'm not a big fan of the appstoreification of Linux as a matter of principle.

**Comment by sp1ritCS** [comment]
> Well, but doesn't the existing automated build already take care of that? It also runs after every commit, rather than being a "nightly".

AFAIK, the current "automated build" only builds **after** a commit to master. This one does this on the pull request.

there was the "old" ci.yml, but that broke as GH's yaml parser got updated.

---

> I'd be happy to set up separate nightly builds for some other families (is the name of libjsoncpp.so the only relevant difference, or are there others?).

For me it is the only difference that ldd cant handle, but I don't know about other distributions.


> I'm still reluctant to make any container-based format the default way Notekit is distributed

are you calling the current automated builds the "default way"? The nightly is obliviously not supposed to be the "default" way, there just to test the latest features until the package maintainer of your distribution has updated the package. - but that is obviously hard if you are unable to run the application.

---

> I think the containers have their role to play for cutting-edge software with very fragile/numerous/exotic dependencies

Funny, I see containerized applications the other way around, as a way to continue to be able to run legacy software (e.g. python2, qt4)

**Comment by blackhole89** [comment]
> AFAIK, the current "automated build" only builds after a commit to master. This one does this on the pull request.

Oh, huh. I didn't realise this, but I guess it makes sense given that there's an explicit on: - pull_request flag in there. I guess I might as well enable it.

> are you calling the current automated builds the "default way"? The nightly is obliviously not supposed to be the "default" way, there just to test the latest features until the package maintainer of your distribution has updated the package. - but that is obviously hard if you are unable to run the application.

It's kind of become the default way, since I haven't updated the explicit releases in a while. Maybe I should think of writing some scripts to automate the release process, too.

> Funny, I see containerized applications the other way around, as a way to continue to be able to run legacy software (e.g. python2, qt4)

I'd count those as "exotic dependencies", but my thought on the matter is that for "daily driver" applications like text editors, you probably shouldn't use ones that depend on legacy frameworks like that. Rather, it's important that you select (and your distro provides you with) one that uses the libraries and integrates with the desktop environments that are made available as part of the distribution, and the distribution has the ultimate responsibility to make sure that those are well-maintained (security and bug fixes etc.). If a text editor I use fails because of a bug in Debian's libjsoncpp1 package, I expect that Debian can and will fix the bug; if it fails because of a bug in a copy of libjsoncpp that got bundled in its container, it's not clear who can actually take responsibility for that (I guess it's technically the author of the text editor or whoever made the container, but expecting them to be able to maintain every dependency on their own is unrealistic; we hardly trust small distros to have healthy packages, what hope is there with individual developers?).

But eh, this is quickly becoming more of a HN debate than a discussion of this PR (and that's completely my own fault), so I'll just go ahead and merge it. Thanks!

**Pull request merged**
